import{a as v,S as P,i as s}from"./assets/vendor-hdXJlIEV.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))d(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function e(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function d(r){if(r.ep)return;r.ep=!0;const a=e(r);fetch(r.href,a)}})();const S="52463480-0d50310a478010cdb93f02561",q="https://pixabay.com/api/";async function u(o,t){try{return(await v.get(q,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(e){throw console.error("Помилка при запиті Pixabay:",e),e}}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more");let M=new P(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),M.refresh()}function x(){f.innerHTML=""}function g(){m.classList.remove("hidden")}function p(){m.classList.add("hidden")}function b(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}const l=document.querySelector(".form"),E=document.querySelector(".load-more");let i="",n=1;const w=15;l.addEventListener("submit",async o=>{if(o.preventDefault(),i=l.elements["search-text"].value.trim(),!i){s.warning({title:"Warning",message:"Please enter a search query"});return}n=1,x(),L(),g();try{const t=await u(i,n);if(t.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}y(t.hits);const e=Math.ceil(t.totalHits/w);n<e?b():s.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}catch(t){console.error("Error fetching images:",t),s.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{p(),l.reset()}});E.addEventListener("click",async()=>{n+=1,L(),g();try{const o=await u(i,n);y(o.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"});const e=Math.ceil(o.totalHits/w);n<e?b():s.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}catch(o){console.error("Error fetching images:",o),s.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{p()}});
//# sourceMappingURL=index.js.map
