import{a as w,S as v,i as s}from"./assets/vendor-hdXJlIEV.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(r){if(r.ep)return;r.ep=!0;const a=e(r);fetch(r.href,a)}})();const q="52463480-0d50310a478010cdb93f02561",P="https://pixabay.com/api/";async function d(o,t){try{return(await w.get(P,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}catch(e){throw console.error("Помилка при запиті Pixabay:",e),e}}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more");let S=new v(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>`).join("");u.insertAdjacentHTML("beforeend",t),S.refresh()}function M(){u.innerHTML=""}function y(){f.classList.remove("hidden")}function g(){f.classList.add("hidden")}function p(){m.classList.remove("hidden")}function b(){m.classList.add("hidden")}const l=document.querySelector(".form"),x=document.querySelector(".load-more");let E="",n=1;const L=15;l.addEventListener("submit",async o=>{o.preventDefault();const t=l.elements["search-text"].value.trim();if(!t){s.warning({title:"Warning",message:"Please enter a search query"});return}n=1,M(),b(),y();try{const e=await d(t);if(e.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}h(e.hits);const i=Math.ceil(e.totalHits/L);n<i?p():s.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}catch(e){console.error("Error fetching images:",e),s.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{g(),searchForm.reset()}});x.addEventListener("click",async()=>{n+=1,b(),y();try{const o=await d(E,n);h(o.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"});const e=Math.ceil(o.totalHits/L);n<e?p():s.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}catch(o){console.error("Error fetching images:",o),s.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{g()}});
//# sourceMappingURL=index.js.map
